---
- name: Install Podman on Debian 12
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Podman
      apt:
        name: podman
        state: present
